name: Deploy React App

on:
  push:
    branches:
      - main  # Change this to your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.15.1'

    - name: Install dependencies
      run: npm install

    - name: Build the React app
      run: npm run build

    - name: pull the latest files in github
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_UNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
          mkdir demo
